-- =========================
-- USERS TABLE
-- =========================
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    password_hash VARCHAR2(4000) NOT NULL,
    phone VARCHAR2(15),
    role VARCHAR2(20) CHECK (role IN ('customer','distributor','admin')),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- =========================
-- CUSTOMER TABLE
-- =========================
CREATE TABLE customer (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER UNIQUE,
    address VARCHAR2(4000),
    city VARCHAR2(100),
    state VARCHAR2(100),
    pincode VARCHAR2(10),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- =========================
-- DISTRIBUTOR TABLE 
-- =========================
CREATE TABLE distributor (
    distributor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER UNIQUE,
    company_name VARCHAR2(150),
    warehouse_location VARCHAR2(4000),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- =========================
-- PRODUCTS TABLE 
-- =========================
CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(150) NOT NULL,
    category VARCHAR2(100) NOT NULL,
    price NUMBER(10,2) NOT NULL CHECK (price > 0),
    distributor_id NUMBER,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (distributor_id) REFERENCES distributor(distributor_id)
);

-- =========================
-- CART TABLE 
-- =========================
CREATE TABLE cart (
    cart_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER,
    product_id NUMBER,
    quantity NUMBER NOT NULL CHECK (quantity > 0),
    FOREIGN KEY (customer_id) REFERENCES customer(customer_id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE,
    UNIQUE (customer_id, product_id)
);

-- =========================
-- ORDER TABLE
-- =========================
CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER,
    order_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    status VARCHAR2(50) CHECK (status IN ('pending','shipped','delivered','cancelled')),
    total_amount NUMBER(10,2) CHECK (total_amount >= 0),
    FOREIGN KEY (customer_id) REFERENCES customer(customer_id)
);

-- =========================
-- ORDER ITEM TABLE
-- =========================
CREATE TABLE order_item (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER,
    product_id NUMBER,
    quantity NUMBER NOT NULL CHECK (quantity > 0),
    price NUMBER(10,2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- =========================
-- PAYMENT TABLE
-- =========================
CREATE TABLE payment (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER UNIQUE,
    payment_method VARCHAR2(50),
    payment_status VARCHAR2(50) CHECK (payment_status IN ('pending','completed','failed')),
    amount NUMBER(10,2) NOT NULL CHECK (amount >= 0),
    payment_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE
);


-- =========================
-- INVENTORY TABLE 
-- =========================
CREATE TABLE inventory (
    inventory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER UNIQUE,
    stock_quantity NUMBER DEFAULT 0 NOT NULL CHECK (stock_quantity >= 0),
    min_stock NUMBER NOT NULL CHECK (min_stock >= 0),
    FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE
);

-- =========================
-- SALES HISTORY TABLE
-- =========================
CREATE TABLE sales_history (
    sales_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER,
    order_id NUMBER,
    quantity_sold NUMBER CHECK (quantity_sold > 0),
    total_price NUMBER(10,2),
    sale_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(product_id),
    FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

-- =========================
-- REVIEW TABLE (FIXED)
-- =========================
CREATE TABLE review (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER,
    product_id NUMBER,
    rating NUMBER CHECK (rating BETWEEN 1 AND 5),
    review_text VARCHAR2(4000), -- Changed from the reserved word 'comment'
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customer(customer_id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE
);

